version: 2

updates:
  # =========================
  # JavaScript
  # =========================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5

    labels:
      - "dependencies"
      - "javascript"

  # =========================
  # Dockerfiles
  # =========================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"

    labels:
      - "dependencies"
      - "docker"

  # =========================
  # Docker Compose
  # =========================
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"

    labels:
      - "dependencies"
      - "docker-compose"

  # =========================
  # GitHub Actions
  # =========================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    labels:
      - "dependencies"
      - "github-actions"